namespace NotSpotify.Api.Models;

/// <summary>
/// One-time password for password reset. Generated by /auth/forgot-password,
/// consumed by /auth/reset-password. Codes expire after 10 minutes and are
/// single-use.
/// </summary>
public class PasswordResetOtp
{
    public Guid Id { get; set; }
    public string Email { get; set; } = string.Empty;
    public string Code { get; set; } = string.Empty;
    public DateTime ExpiresAt { get; set; }
    public bool IsUsed { get; set; }
}
