using System.ComponentModel.DataAnnotations.Schema;

namespace NotSpotify.Api.Models;

/// <summary>
/// One-time password for password reset. Generated by /auth/forgot-password,
/// consumed by /auth/reset-password. Codes expire after 10 minutes and are
/// single-use.
///
/// The plaintext 6-digit code is only ever emailed to the user — the database
/// stores an HMAC-SHA256 hash (keyed with the JWT signing key), so a leaked
/// dump can't be used to reset accounts. This mirrors the registration OTP
/// (see <see cref="Services.RegistrationVerificationService"/>).
/// </summary>
public class PasswordResetOtp
{
    public Guid Id { get; set; }
    public string Email { get; set; } = string.Empty;

    /// <summary>HMAC hash of the emailed code. Mapped to the legacy "Code" column
    /// so no destructive schema change is needed on existing databases.</summary>
    [Column("Code")]
    public string CodeHash { get; set; } = string.Empty;

    public DateTime ExpiresAt { get; set; }

    /// <summary>When the code was issued — drives the resend cooldown.</summary>
    public DateTime SentAt { get; set; }

    public bool IsUsed { get; set; }
}
